trigger:
  - main

pr:
  - main

pool:
  name: BalutaAgentPool
  demands:
    - docker

variables:
  imageName: 'static-web'
  imageTag: '$(Build.BuildId)'
  containerName: 'static-web-$(Build.BuildId)'
  hostPort: '8080'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: BuildImage
    displayName: Build Docker image
    steps:
    - checkout: self
    - script: |
        set -eux
        docker build -t $(imageName):$(imageTag) -f Dockerfile .
        docker images | head -n 20
      displayName: docker build

- stage: Deploy
  displayName: Run container locally
  dependsOn: Build
  jobs:
  - deployment: DeployLocal
    displayName: Start container on agent
    environment: 'local'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              set -eux
              #Remove previous containers
              for c in $(docker ps -aq --filter "name=static-web-"); do docker rm -f "$c" || true; done

              # Run the new container
              docker run -d --name $(containerName) -p $(hostPort):80 $(imageName):$(imageTag)

              # Probe readiness
              for i in {1..15}; do
                if curl -fsS http://localhost:$(hostPort) >/dev/null; then
                  echo "App is up on http://localhost:$(hostPort)"
                  exit 0
                fi
                sleep 2
              done
              echo "App failed health check" >&2
              docker logs $(containerName) || true
              exit 1
            displayName: Run & health check
          - script: docker ps
            displayName: Show running containers
