# jenkins-rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-agent
  namespace: default
rules:
  # Jenkins K8s plugin needs to create/list/watch/patch/delete agent pods and exec/log into them
  - apiGroups: [""]
    resources: ["pods","pods/exec","pods/log","secrets"]
    verbs: ["get","list","watch","create","update","patch","delete"]
  # read services/endpoints for in-cluster URL resolution
  - apiGroups: [""]
    resources: ["services","endpoints"]
    verbs: ["get","list","watch"]
  # events write for nicer troubleshooting
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create","patch","update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-agent-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-agent
