# jenkins-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: default
spec:
  type: ClusterIP
  selector:
    workload.user.cattle.io/workloadselector: pod-default-jenkinspod
  ports:
  - name: http
    port: 8080
    targetPort: 8080
