name: Local build & run (Windows self-hosted)
on: [workflow_dispatch, push]

permissions:
  contents: read

env:
  IMAGE_NAME: myapp
  DOCKERFILE: Dockerfile
  PORT: "80"      # container port
  HOST_PORT: "8099" # host port

jobs:
  local:
    runs-on: [self-hosted, windows, docker]
    defaults: { run: { shell: pwsh } }
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: |
          $env:TAG = "${{ github.sha }}"
          docker build -f "$env:DOCKERFILE" -t "$env:IMAGE_NAME:$env:TAG" .
          "TAG=$($env:TAG)" | Out-File -FilePath $env:GITHUB_ENV -Append
      - name: Replace running container
        run: |
          if (docker ps -a --format '{{.Names}}' | Select-String -SimpleMatch $env:IMAGE_NAME) {
            docker stop $env:IMAGE_NAME 2>$null; docker rm $env:IMAGE_NAME 2>$null
          }
          docker run -d --name $env:IMAGE_NAME `
            -p "$env:HOST_PORT`:$env:PORT" `
            "$env:IMAGE_NAME`:$env:TAG"
      - name: Show status / URL
        run: |
          docker ps --filter "name=$env:IMAGE_NAME"
          "Open: http://localhost:$env:HOST_PORT" | Out-Host
