name: Local build & run (self-hosted)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: read

env:
  IMAGE_NAME: homeworkaction
  DOCKERFILE: Dockerfile
  PORT: "80"
  HOST_PORT: "8099"

jobs:
  local:
    runs-on: [self-hosted, docker]
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: |
          set -euo pipefail
          TAG=${{ github.sha }}
          docker build -f "$DOCKERFILE" -t "$IMAGE_NAME:$TAG" .
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Replace running container
        run: |
          set -euo pipefail
          docker ps -a --format '{{.Names}}' | grep -q '^${{ env.IMAGE_NAME }}$' && \
            (docker stop ${{ env.IMAGE_NAME }} || true; docker rm ${{ env.IMAGE_NAME }} || true) || true
          docker run -d --name ${{ env.IMAGE_NAME }} \
            -p $HOST_PORT:$PORT \
            --restart unless-stopped \
            "$IMAGE_NAME:$TAG"

      - name: Show status
        run: |
          docker ps --filter "name=${{ env.IMAGE_NAME }}"
          echo "Open: http://localhost:${{ env.HOST_PORT }}"
